# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=serial
endif
export config

PROJECTS := LuaRPC

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

LuaRPC: 
	@echo ==== Building LuaRPC ====
	@${MAKE} --no-print-directory -C . -f LuaRPC.make

clean:
	@${MAKE} --no-print-directory -C . -f LuaRPC.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   serial"
	@echo "   socket"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LuaRPC"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
